#!/bin/bash

cd "$(dirname $0)"

compose_file="./stuck.yaml"

function start() 
{
    source .env
    echo -n "${TRAEFIK_DASHBORD_USER}:traefik:$(echo -n "${TRAEFIK_DASHBORD_USER}:traefik:${TRAEFIK_DASHBORD_PSWD}" | md5sum | awk '{print $1}')" > ./config/traefik/password && chmod 600 ./config/traefik/password
    echo -n "${PORTAINER_PSWD}" > ./config/portainer/password && chmod 600 ./config/portainer/password
    docker-compose -f $compose_file up -d
}

function stop()
{
    docker-compose -f $compose_file down
}

function try_mkdir()
{
    for dir_path in $*
    do
        if [ ! -d $dir_path ]; then mkdir -p $dir_path; fi
    done
}

case $1 in
"build")
    try_mkdir ./www && chgrp 33 ./www && chmod g+s ./www
    try_mkdir ./www/html ./database/mysql ./database/portainer ./database/redis ./log/nginx ./log/traefik
    touch ./www/html/do_not_delete
    touch ./config/traefik/acme_staging.json && chmod 600 ./config/traefik/acme_staging.json
    touch ./config/traefik/acme_production.json && chmod 600 ./config/traefik/acme_production.json
    docker-compose -f $compose_file build php8.0-fpm workspace
    docker-compose -f $compose_file pull nginx mysql traefik redis portainer adminer
;;
"start")
    start
;;
"dev")
    docker-compose -f $compose_file run --rm workspace
;;
"stop")
    stop
;;
"restart")
    stop
    start
;;
*)
    echo "Usage: ./server [build|start|dev|stop|restart]"
;;
esac
