version: '3.8'

services:
  nginx:
    image: 'nginx:stable'
    volumes:
      - './www:/var/www'
      - './config/nginx/nginx.conf:/etc/nginx/nginx.conf'
      - './config/nginx/sites-available:/etc/nginx/sites-available'
      - './config/nginx/presets:/etc/nginx/presets'
      - './config/nginx/snippets:/etc/nginx/snippets'
      - './log/nginx/:/var/log/nginx'
    restart: on-failure

  php-fpm:
    build: './build/php-fpm'
    volumes:
      - './www:/var/www'
      - './config/php-fpm/custom.ini:/usr/local/etc/php/conf.d/custom.ini'
    restart: on-failure

  mysql:
    image: 'mysql:8.0'
    volumes:
      - './data/mysql:/var/lib/mysql'
      - './config/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf'
    environment:
      - 'MYSQL_RANDOM_ROOT_PASSWORD=yes'
    ports:
      - '3306:3306'
    restart: on-failure

  redis:
    image: 'redis:6.2'
    volumes:
      - './data/redis:/data'
      - './config/redis/redis.conf:/usr/local/etc/redis/redis.conf'
    command: 'redis-server /usr/local/etc/redis/redis.conf'
    restart: on-failure

  workspace:
    build: './build/workspace'
    volumes:
      - './www:/var/www'
      - './config/php-fpm/custom.ini:/usr/local/etc/php/conf.d/custom.ini'
    profiles:
      - workspace

  caddy:
    build:
      context: './build/caddy'
      args:
        - 'GOPROXY=${GO_MODULE_MIRROR}'
    volumes:
      - './config/caddy/Caddyfile:/etc/caddy/Caddyfile'
      - './data/caddy/data:/data'
      - './data/caddy/config:/config'
      - './config/caddy/snippets:/etc/caddy/snippets'
      - './config/caddy/sites-proxied:/etc/caddy/sites-proxied'
      - './config/caddy/modes:/etc/caddy/modes'
      - './log/caddy:/var/log/caddy'
    ports:
      - '80:80'
      - '443:443'
    environment:
      - 'ACME_EMAIL=${ACME_EMAIL}'
      - 'DEPLOY_MODE=${DEPLOY_MODE}'
    restart: on-failure
