version: '3'

services:
  ### Nginx ############################################
  nginx:
    image: 'nginx:alpine'
    volumes:
      - './www:/var/www'
      - './config/nginx/nginx.conf:/etc/nginx/nginx.conf'
      - './config/nginx/sites-available:/etc/nginx/sites-available'
      - './config/nginx/includes:/etc/nginx/includes'
      - './log/nginx/:/var/log/nginx'

  ### PHP-FPM ############################################
  php8.0-fpm:
    build: './build/php-fpm/8.0'
    volumes:
      - './www:/var/www'
      - './config/php-fpm/8.0/custom.ini:/usr/local/etc/php/conf.d/custom.ini'

  ### MySQL ############################################
  mysql:
    image: 'mysql:8.0'
    volumes:
      - './database/mysql:/var/lib/mysql'
      - './config/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf'
    environment:
      - 'MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}'

  ### traefik ############################################
  traefik:
    image: 'traefik:2.6'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './config/traefik:/etc/traefik'
      - './log/traefik:/var/log/traefik'
    environment:
      - 'TRAEFIK_GLOBAL_CHECKNEWVERSION=${TRAEFIK_CHECKNEWVERSION}'
      - 'TRAEFIK_GLOBAL_SENDANONYMOUSUSAGE=false'
      - 'TRAEFIK_LOG=true'
      - 'TRAEFIK_LOG_FILEPATH=/var/log/traefik/traefik.log'
      - 'TRAEFIK_LOG_LEVEL=ERROR'
      - 'TRAEFIK_API=true'
      - 'TRAEFIK_API_DASHBOARD=true'
      - 'TRAEFIK_ENTRYPOINTS_unsecured=true'
      - 'TRAEFIK_ENTRYPOINTS_unsecured_ADDRESS=:80'
      - 'TRAEFIK_ENTRYPOINTS_secured=true'
      - 'TRAEFIK_ENTRYPOINTS_secured_ADDRESS=:443'
      - 'TRAEFIK_CERTIFICATESRESOLVERS_staging=true'
      - 'TRAEFIK_CERTIFICATESRESOLVERS_staging_ACME_EMAIL=${ACME_EMAIL}'
      - 'TRAEFIK_CERTIFICATESRESOLVERS_staging_ACME_STORAGE=/etc/traefik/acme_staging.json'
      - 'TRAEFIK_CERTIFICATESRESOLVERS_staging_ACME_CASERVER=https://acme-staging-v02.api.letsencrypt.org/directory'
      - 'TRAEFIK_CERTIFICATESRESOLVERS_staging_ACME_HTTPCHALLENGE=true'
      - 'TRAEFIK_CERTIFICATESRESOLVERS_staging_ACME_HTTPCHALLENGE_ENTRYPOINT=unsecured'
      - 'TRAEFIK_CERTIFICATESRESOLVERS_production=true'
      - 'TRAEFIK_CERTIFICATESRESOLVERS_production_ACME_EMAIL=${ACME_EMAIL}'
      - 'TRAEFIK_CERTIFICATESRESOLVERS_production_ACME_STORAGE=/etc/traefik/acme_production.json'
      - 'TRAEFIK_CERTIFICATESRESOLVERS_production_ACME_CASERVER=https://acme-v02.api.letsencrypt.org/directory'
      - 'TRAEFIK_CERTIFICATESRESOLVERS_production_ACME_HTTPCHALLENGE=true'
      - 'TRAEFIK_CERTIFICATESRESOLVERS_production_ACME_HTTPCHALLENGE_ENTRYPOINT=secured'
      - 'TRAEFIK_PROVIDERS_FILE_DIRECTORY=/etc/traefik/dynamic_conf'
      - 'TRAEFIK_PROVIDERS_FILE_WATCH=true'
      - 'DEFAULT_CERT_RESOLVER=${DEFAULT_CERT_RESOLVER}'
      - 'TRAEFIK_DASHBORD_DOMAIN=${TRAEFIK_DASHBORD_DOMAIN}'
      - 'PORTAINER_DOMAIN=${PORTAINER_DOMAIN}'
      - 'ADMINER_DOMAIN=${ADMINER_DOMAIN}'

  ### redis ############################################
  redis:
    image: 'redis:6.2-alpine'
    volumes:
      - './database/redis:/data'
      - './config/redis/redis.conf:/usr/local/etc/redis/redis.conf'
    command: 'redis-server /usr/local/etc/redis/redis.conf'

  ### workspace ############################################
  workspace:
    build: './build/workspace'
    volumes:
      - './www:/var/www'
    profiles:
      - workspace

  ### Portainer ############################################
  portainer:
    image: 'portainer/portainer-ce:alpine'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './database/portainer:/data'
      - './config/portainer/password:/tmp/portainer_password'
    command: '--admin-password-file /tmp/portainer_password'

  ### Adminer ############################################
  adminer:
    image: 'adminer:standalone'
    environment:
      - 'ADMINER_DESIGN=pepa-linha'
